# Generated by Django 5.0.3 on 2024-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicant_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='applicant_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='applicant_phone',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor_phone',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_contact_person',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_contact_person_mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.CharField(max_length=100),
        ),
    ]
