# Generated by Django 5.0.3 on 2024-03-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_applicant_email_project_applicant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantMentorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default='', max_length=50)),
                ('applicant_email', models.EmailField(default='', max_length=254)),
                ('applicant_phone', models.CharField(default='', max_length=25)),
                ('mentor_name', models.CharField(default='', max_length=50)),
                ('mentor_email', models.EmailField(default='', max_length=254)),
                ('mentor_phone', models.CharField(default='', max_length=25)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_mentor_details', to='myapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='', max_length=100)),
                ('organization_contact_person', models.CharField(default='', max_length=50)),
                ('organization_contact_person_mail', models.EmailField(default='', max_length=254)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_details', to='myapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('project_duration', models.IntegerField(choices=[(2, 2), (3, 3)])),
                ('field', models.CharField(choices=[('Natural studies', 'Natural studies'), ('Engineering and technology', 'Engineering and technology'), ('Medical and health sciences', 'Medical and health sciences'), ('Agricultural sciences', 'Agricultural sciences'), ('Social sciences', 'Social sciences'), ('Humanities', 'Humanities')], max_length=50)),
                ('keywords', models.CharField(max_length=100)),
                ('undesirable_expert', models.CharField(max_length=100)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='myapp.project')),
            ],
        ),
    ]
