# Generated by Django 5.0.3 on 2024-03-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_applicantmentordetails_organizationdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmentordetails',
            name='applicant_email',
        ),
        migrations.RemoveField(
            model_name='applicantmentordetails',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='applicantmentordetails',
            name='applicant_phone',
        ),
        migrations.RemoveField(
            model_name='applicantmentordetails',
            name='mentor_email',
        ),
        migrations.RemoveField(
            model_name='applicantmentordetails',
            name='mentor_name',
        ),
        migrations.RemoveField(
            model_name='applicantmentordetails',
            name='mentor_phone',
        ),
        migrations.RemoveField(
            model_name='organizationdetails',
            name='organization_contact_person',
        ),
        migrations.RemoveField(
            model_name='organizationdetails',
            name='organization_contact_person_mail',
        ),
        migrations.RemoveField(
            model_name='organizationdetails',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='field',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='project_duration',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='undesirable_expert',
        ),
    ]
